package com.dumpster_sensor.webapp.models;

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;

@Entity
@Table(name = "garbage")
public class Garbage {
    //PK. Autogenerated in DB
    @Id
    @Column(nullable = false, unique = true)
    @GeneratedValue
    private Long id;

    @Column(nullable = false)
    private Long sensorID;

    @Column(nullable = false)
    private int garbageLevel;

    @Column(nullable = false)
    private String time;

    public Garbage() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSensorID() {
        return sensorID;
    }

    public void setSensorID(Long sensorID) {
        this.sensorID = sensorID;
    }

    public int getGarbageLevel() {
        return garbageLevel;
    }

    public void setGarbageLevel(int garbageLevel) {
        this.garbageLevel = garbageLevel;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }
}
