package com.dumpster_sensor.webapp.models;

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;

@Entity
@Table(name = "sensor")

public class Sensor {
    //PK. Autogenerated in DB
    @Id
    @Column(nullable = false, unique = true)
    @GeneratedValue
    private Long id;

    @Column(nullable = false, length = 45)
    private String location;

    @Column(nullable = true, length = 45)
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm")
    private java.util.Date time1;

    @Column(nullable = true, length = 45)
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm")
    private java.util.Date time2;

    @Column
    private boolean installed;

    //not sure if this needs to be a string but for now it is a string
    @Column
    private String power;

    @Column(nullable = true, length = 45)
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm")
    private java.util.Date lastUpdated;
}
