package com.dumpster_sensor.webapp.models;

import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.*;
import java.util.Date;

@Entity
@Table(name = "sensor")

public class Sensor {
    //PK. Autogenerated in DB
    @Id
    @Column(nullable = false, unique = true)
    @GeneratedValue
    private Long id;

    @Column(nullable = false, length = 45)
    private String location;

    @Column(nullable = false)
    private String time1;

    @Column(nullable = false)
    private String time2;

    @Column(nullable = false, length = 45)
    private String installed;

    //not sure if this needs to be a string but for now it is a string
    @Column
    private String power;

    @Column
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm")
    private java.util.Date lastUpdated;

    public Sensor() {
    }

    public Sensor(Long id, String location, String time1, String time2, String installed, String power, Date lastUpdated) {
        this.id = id;
        this.location = location;
        this.time1 = time1;
        this.time2 = time2;
        this.installed = installed;
        this.power = power;
        this.lastUpdated = lastUpdated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getTime1() {
        return time1;
    }

    public void setTime1(String time1) {
        this.time1 = time1;
    }

    public String getTime2() {
        return time2;
    }

    public void setTime2(String time2) {
        this.time2 = time2;
    }

    public String getInstalled() {
        return installed;
    }

    public void setInstalled(String installed) {
        this.installed = installed;
    }

    public String getPower() {
        return power;
    }

    public void setPower(String power) {
        this.power = power;
    }

    public Date getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}
